#26 翻译 exploring istio telemetry and observability
servicemesher/website pull request #33
Opened 2019-05-27 09:05 UTC by chengwhynot

请审校者在合并该 PR 前需要检查以下内容：

- [ ] Header 设置正确，包括文章的类型、tag、分类、作者、译者、摘要、reviewer 发布时间等信息
- [ ] 关联 Issue 编号 https://github.com/servicemesher/trans/issues/${ISSUE_ID}
- [ ] 该 PR Assigned 给了提交者
- [ ] 指定了 Reviewer
- [ ] 为 PR 明确了 label 信息，如 categories、kind、size、tag、status
- [ ] 所有代码片段都指定了代码语言
- [ ] 翻译的文章添加了**编者按**
- [ ] 文章遵守了路径规范  `YEAR/MONTH/TITLE/index.md`，例如 `2019/04/new-blog/index.md`
- [ ] 图片保存了在 GitHub上，跟文章在同级目录
- [ ] 文章标题简短且语义明确
- [ ] 文章语句通顺，没有语病和格式问题
- [ ] 文中没有不可达的链接
- [ ] 提交者同意授权 ServiceMesher 公众号和 http://www.servicemesher.com 发布我原创或翻译的文章

当所有以上问题都确定之后，可以由管理者合并 PR 并关闭关联 issue。

2019-05-27 09:10 UTC, chengwhynot commented
那个spell check被忽略了，是故意的么？还是脚本错了？看提示和脚本的意思是PR不能被忽略的。

2019-05-27 10:37 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +```
内嵌代码应该知道代码语言

2019-05-27 10:38 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +```
```->```yaml

2019-05-27 10:48 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +[Banzai Cloud]（https://banzaicloud.com/）改变私有云的构建方式，以简化复杂应用程序的开发，部署和扩展，将Kubernetes和Cloud Native技术的全部功能带给各地的开发人员和企业。
（https://banzaicloud.com/），这里括号是不是有问题，应该是中文括号

2019-05-27 10:57 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +Istio的一个核心功能就是网络流量的可观察性。因为所有服务间的通信都通过Envoy代理，而且Istio的控制平面可以从这些代理收集日志和指标，服务网格能够让你深入了解你的网络状况。虽然Istio的基本安装就装好了收集遥测数据所需的全部组件，但是理解这些组件如何配合，并且使他们能够工作在生产环境中却不是一个容易的事情。如果服务网格扩展到跨越多个云服务提供商的多个群集时，或者在一个混合情况下，甚至
并且会完整浏览的一些监控例子->并且会完整浏览一些监控例子

2019-05-27 10:59 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +Istio的一个核心功能就是网络流量的可观察性。因为所有服务间的通信都通过Envoy代理，而且Istio的控制平面可以从这些代理收集日志和指标，服务网格能够让你深入了解你的网络状况。虽然Istio的基本安装就装好了收集遥测数据所需的全部组件，但是理解这些组件如何配合，并且使他们能够工作在生产环境中却不是一个容易的事情。如果服务网格扩展到跨越多个云服务提供商的多个群集时，或者在一个混合情况下，甚至
operator翻译为运营者不太合适，可以不翻译

2019-05-27 12:44 UTC, rootsongjc commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +Istio的一个核心功能就是网络流量的可观察性。因为所有服务间的通信都通过Envoy代理，而且Istio的控制平面可以从这些代理收集日志和指标，服务网格能够让你深入了解你的网络状况。虽然Istio的基本安装就装好了收集遥测数据所需的全部组件，但是理解这些组件如何配合，并且使他们能够工作在生产环境中却不是一个容易的事情。如果服务网格扩展到跨越多个云服务提供商的多个群集时，或者在一个混合情况下，甚至
同意，这个应该作为专有名词，不用翻译。

2019-05-27 12:44 UTC, rootsongjc commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +>作者是BANZA CLOUD的工程师，文章介绍了istio环境下，如何结合Prometheus进行网络度量指标监测，给出了一些示例配置。最后，还推广了一下BANZA CLOUD自家的PIPELINE，天然支持跨云、混合云情况下的网络度量监测，欢迎体验。
Banzai Cloud，不是 Banza Cloud。

2019-05-27 14:54 UTC, GuangmingLuo commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +summary: "文章介绍了istio环境下，如何结合Prometheus进行网络度量指标监测，给出了一些示例配置。最后，还推广了一下BANZA CLOUD自家的PIPELINE，天然支持跨云、混合云情况下的网络度量监测，欢迎体验。"
BANZAI CLOUD

2019-05-27 14:54 UTC, GuangmingLuo commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +Istio的一个核心功能就是网络流量的可观察性。因为所有服务间的通信都通过Envoy代理，而且Istio的控制平面可以从这些代理收集日志和指标，服务网格能够让你深入了解你的网络状况。虽然Istio的基本安装就装好了收集遥测数据所需的全部组件，但是理解这些组件如何配合，并且使他们能够工作在生产环境中却不是一个容易的事情。如果服务网格扩展到跨越多个云服务提供商的多个群集时，或者在一个混合情况下，甚至
或者在一个混合情况下 -> 或者在混合云情况下

2019-05-27 14:54 UTC, GuangmingLuo commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +应用pod的sidecar在发起每一个请求前调用`istio-policy`来进行前置条件检查，并在请求结束后发送遥测数据。sidecar本地缓存了一大批前置检查，使得大量的检查只需要通过缓存就能获得结果。额外的，sidecar还对输出的遥测数据进行了缓冲，以减少调用mixer的频率。
额外的 -> 此外

2019-05-27 14:54 UTC, GuangmingLuo commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +Istio的文档列举了[收集自定义指标](https://istio.io/docs/tasks/telemetry/metrics/collecting-metrics/)，以及[从Prometheus中查询指标](https://istio.io/docs/tasks/telemetry/metrics/querying-metrics/)的例子，但缺少一个重要的内容：理解和配置Promet
理解和配置Prometheus的手机目标 -> 理解和配置Prometheus的收集目标

2019-05-27 14:54 UTC, GuangmingLuo commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +如果你只是想试一试Istio，多半你会部署了它的官方图表工具Helm（我们更推荐[Istio operator](https://github.com/banzaicloud/istio-operator)以获取更好的体验）。Helm图表默认包含了Prometheus部署并且也已经配置好。但是在生产环境下，你通常需要自定义设置Prometheus以及配置它的收集目标。这样情况下，你需要手工将Is
多半你会部署了它的官方图表工具Helm -> 多半你会部署它的官方工具Helm Chart

2019-05-27 14:54 UTC, GuangmingLuo commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +如果你只是想试一试Istio，多半你会部署了它的官方图表工具Helm（我们更推荐[Istio operator](https://github.com/banzaicloud/istio-operator)以获取更好的体验）。Helm图表默认包含了Prometheus部署并且也已经配置好。但是在生产环境下，你通常需要自定义设置Prometheus以及配置它的收集目标。这样情况下，你需要手工将Is
文章中的"Helm图表” 建议不翻译，直接使用 Helm Chart

2019-05-28 01:54 UTC, haiker2011 requested changes

2019-05-28 01:54 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +应用pod的sidecar在发起每一个请求前调用`istio-policy`来进行前置条件检查，并在请求结束后发送遥测数据。sidecar本地缓存了一大批前置检查，使得大量的检查只需要通过缓存就能获得结果。额外的，sidecar还对输出的遥测数据进行了缓冲，以减少调用mixer的频率。
缓冲->缓存

2019-05-28 01:54 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +如果你想用一个不同的`适配器` - 如`Stackdriver`- 你需要更新mixer的自定义资源配置。Istio中有几个概念叫做`处理器`，`实例`以及`规则`。`处理器`决定一系列后端基础设置适配器是怎么工作以及如何操作的，`实例`描述了如何把请求的属性映射到适配器的输入上，最后`规则`把`处理器`和`实例`拼接在一起。这些概念如果你想了解更多，你可以查看[官方文档](https://is
Handlers翻译为处理器不太合适吧？专有名词可以不翻译

2019-05-28 01:54 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +Istio的文档列举了[收集自定义指标](https://istio.io/docs/tasks/telemetry/metrics/collecting-metrics/)，以及[从Prometheus中查询指标](https://istio.io/docs/tasks/telemetry/metrics/querying-metrics/)的例子，但缺少一个重要的内容：理解和配置Promet
手机->收集？

2019-05-28 01:54 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +最重要的两个目标是`istio-mesh`和`envoy-stats`。Including the first one in `prometheus.yml` will allow Prometheus to scrape `Mixer`, where service-centric telemetry data is provided about all network traffic bet
有一句没有翻译

2019-05-28 01:54 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +```
jons等名词中文翻译尽量单数

2019-05-28 01:54 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +Banzai Cloud的[Pipeline](https://github.com/banzaicloud/pipeline)提供了一个平台，允许企业开发，部署和扩展基于容器的应用程序。 它利用最佳的云组件（如Kubernetes）为开发人员和运维团队创建高效，灵活的环境。 强大的安全措施 - 多身份验证后端，细粒度授权，动态秘密管理，使用TLS的组件之间的自动安全通信，漏洞扫描，静态代码分析
动态秘密管理->动态密钥管理

2019-05-28 02:56 UTC, chengwhynot commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +如果你想用一个不同的`适配器` - 如`Stackdriver`- 你需要更新mixer的自定义资源配置。Istio中有几个概念叫做`处理器`，`实例`以及`规则`。`处理器`决定一系列后端基础设置适配器是怎么工作以及如何操作的，`实例`描述了如何把请求的属性映射到适配器的输入上，最后`规则`把`处理器`和`实例`拼接在一起。这些概念如果你想了解更多，你可以查看[官方文档](https://is
这几个instances, rules, handlers都不翻译了

2019-05-28 03:07 UTC, chengwhynot commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +[Banzai Cloud]（https://banzaicloud.com/）改变私有云的构建方式，以简化复杂应用程序的开发，部署和扩展，将Kubernetes和Cloud Native技术的全部功能带给各地的开发人员和企业。
是的，修改为英文括号了

2019-05-28 04:42 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +首先，我们来看看这些目标。如果你打开这里的配置，你会发现Istio给Prometheus添加了十多个job。大部分是从Istio控制平面收集自定义指标的。你可以看到Pilot通过类似`pilot_xds_pushes`, `pilot_xds_push_timeout` and `pilot_total_xds_internal_errors`这些指标上报遥测数据，如`xDS`推送，超时或内部错
and没有翻译

2019-05-28 12:36 UTC, chengwhynot commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +首先，我们来看看这些目标。如果你打开这里的配置，你会发现Istio给Prometheus添加了十多个job。大部分是从Istio控制平面收集自定义指标的。你可以看到Pilot通过类似`pilot_xds_pushes`, `pilot_xds_push_timeout` and `pilot_total_xds_internal_errors`这些指标上报遥测数据，如`xDS`推送，超时或内部错
fixed

2019-05-28 12:37 UTC, chengwhynot commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +首先，我们来看看这些目标。如果你打开这里的配置，你会发现Istio给Prometheus添加了十多个job。大部分是从Istio控制平面收集自定义指标的。你可以看到Pilot通过类似`pilot_xds_pushes`, `pilot_xds_push_timeout` and `pilot_total_xds_internal_errors`这些指标上报遥测数据，如`xDS`推送，超时或内部错
眼神真好

2019-05-29 09:03 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +categories: "译文"
categories: "译文"，类型不用翻译，直接保留translation

2019-05-29 09:08 UTC, haiker2011 commented on content/blog/exploring-istio-telemetry-and-observability/index.md
> +categories: "译文"
这个头其实你可以按照最新的，省得再修改，使用如下：
---
title: ""
date: 2019-05-27T4:55:44+08:00
draft: false
banner: ""
author: ""
authorlink: ""
translator: ""
translatorlink: ""
reviewer:  [""]
reviewerlink:  ""
originallink: ""
summary: ""
tags: ["servicemesh", "Envoy"]
categories: ["translation"]
keywords: ["servicemesh", "Envoy"]
aliases: "/blog/"
---

2019-05-30 01:26 UTC, merged