开源，社区与朋友们-2019 KubeCon + ClondNativeCon + Open Source Summit有感
servicemesher/website pull request #54
Opened 2019-06-28 03:49 UTC by zhaohuabing

请审校者在合并该 PR 前需要检查以下内容：

- [ ] Header 设置正确，包括文章的类型、tag、分类、作者、译者、摘要、reviewer 发布时间等信息
- [ ] 关联 Issue 编号 [#${ISSUE_ID}](https://github.com/servicemesher/website/issues/${ISSUE_ID})
- [ ] 该 PR Assigned 给了提交者
- [ ] 指定了 Reviewer
- [ ] 为 PR 明确了 label 信息，如 categories、kind、size、tag、status
- [ ] 所有代码片段都指定了代码语言
- [ ] 翻译的文章添加了**编者按**
- [ ] 文章遵守了路径规范  `YEAR/MONTH/TITLE/index.md`，例如 `2019/04/new-blog/index.md`
- [ ] 图片保存了在 GitHub上，跟文章在同级目录
- [ ] 文章标题简短且语义明确
- [ ] 文章语句通顺，没有语病和格式问题
- [ ] 文中没有不可达的链接
- [ ] 提交者同意授权 ServiceMesher 公众号和 [http://www.servicemesher.com](http://www.servicemesher.com) 发布我原创或翻译的文章

当所有以上问题都确定之后，可以由管理者合并 PR 并关闭关联 issue。

2019-06-28 05:35 UTC, haiker2011 requested changes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +从他的演讲中可以感受到来自中国的公司和开发者在开源软件，特别是云原生领域中发挥了越来越重要的作用。由于中国的市场体量很大，中国公司在在使用开源软件时会面临一些国外难以遇到的问题，例如如何应对数以亿记的用户量。在解决这些问题的同时，很多中国公司也将这些优化和改进贡献到了上游项目，造福整个开源社区，形成了良性的互动和循环。从后面两天的主题演讲，我也看到中国公司，特别是阿里系在回馈上游开源社区方面是做
亿记->亿计

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +summary: "奇妙的 2019 KubeCon + ClondNativeCon + Open Source Summit 大会！在这里，我近距离接触了大神 Linus；见到了自 ServiceMesher 社区的很多朋友；还遇到了搞 Kubernets 的恩格斯后人！"
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +* 中国已经成为第二大Kubernets贡献者
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +HashiCorp的方案主要是面向多云环境以及同时存在Kubernets和VM，bare metal场景的企业用户。其方案和我们目前自己使用的方案比较类似，后面值得长期关注。如果希望了解更多Consul Connect的内容，可以关注HashiCorp的博客及网站： <https://www.hashicorp.com/blog/layer-7-observability-with-consul
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +介绍了Kubernets Ingress的局限性和Contour的解决方案：采用一个新的CRD。Ingress的局限性一直为社区所诟病，Kubernets中的Ingress只是七层代理的一个最小集合，为了解决该问题，几乎每个Ingress Controller项目都使用了自定义的扩展，包括Annotation和自定义CRD两种方式。
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +* 是否会把IngressRoute CRD中的特性贡献到Kubernets社区，他答复说可能会在Kubernets Ingress的下一个版本中加入部分新特性。
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +其实各个具体的产品对Ingress的要求各不相同，如何在Kubernets自身API的简洁性和产品要求的功能实用性之间进行平衡是一个难题，因此该问题应该还会存在很长时间。我的建议是采用一个API Gateway + Sidecar 来代替 Kubernets Ingress，参见我之前的文章[如何为服务网格选择入口网关？](https://zhaohuabing.com/post/2019-03
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +### 恩格斯也来搞Kubernets了！
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +聊了一会儿后，他指着自己胸牌上的名字问到，你知道恩格斯吗？我一时还没有回过神来，他又问了一次，你知道恩格斯吗？他在中国很有名的。我这才想起，问到：是那个搞共产主义的恩格斯吗？他兴奋地说，是的，他是我曾曾曾祖父的侄子。What a small world！没想到恩格斯家族也来搞Kubernets了。不过Kubernets的理念和恩格斯、马克思提出的那个世界大同的理想是不是也很相似呢？
Kubernets->Kubernetes

2019-06-28 05:35 UTC, haiker2011 commented on content/blog/kubecon-cncf-oss-2019/index.md
> +* Kubernets已经成为云上的标准，Cloud Native正当时：这个观点是阿里在演讲中提出来的，我非常赞同。从这次大会的参展厂商和技术分享中可以看到，几乎所有的云厂商/运营商/企业都已经采用了容器和Kubernets，并且在积极推进Service Mesh等云原生技术栈的实践和运用。
Kubernets->Kubernetes

2019-06-28 06:11 UTC, zhaohuabing commented
content/blog/kubecon-cncf-oss-2019/index.md:17: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:26: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:44: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:75: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:79: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:92: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:96: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:105: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:117: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:130: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:132: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:139: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:146: MD022 Headers should be surrounded by blank lines
content/blog/kubecon-cncf-oss-2019/index.md:154: MD022 Headers should be surrounded by blank lines
规则是不是有点问题？ 标题前后是有空白行的。

2019-06-28 06:36 UTC, haiker2011 commented
@zhaohuabing 嗯嗯，我也看了一下，感觉确实有点问题，格式先忽略吧

2019-06-28 07:44 UTC, SataQiu reviewed
好文！

2019-06-28 07:44 UTC, SataQiu commented on content/blog/kubecon-cncf-oss-2019/index.md
> +summary: "奇妙的 2019 KubeCon + ClondNativeCon + Open Source Summit 大会！在这里，我近距离接触了大神 Linus；见到了自 ServiceMesher 社区的很多朋友；还遇到了搞 Kubernetes 的恩格斯后人！"
```suggestion
summary: "奇妙的 2019 KubeCon + ClondNativeCon + Open Source Summit 大会！在这里，我近距离接触了大神 Linus；见到了来自 ServiceMesher 社区的很多朋友；还遇到了搞 Kubernetes 的恩格斯后人！"
```

2019-06-29 02:38 UTC, zhaohuabing commented
还有需要修改的吗？

2019-06-29 03:41 UTC, SataQiu approved these changes

2019-06-29 06:25 UTC, haiker2011 approved these changes

2019-06-29 08:57 UTC, merged