添加dashboard文章
servicemesher/website pull request #7
Opened 2019-04-14 14:36 UTC by zhangguanzhang

字段图床均已按照要求修改，同时修改之前投稿的错别字和添加一行注意

2019-04-15 02:07 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard
> +title: "dashboard在ssl的各种场景下的手动部署"
标题需要指明究竟是什么的 dashboard

2019-04-15 02:08 UTC, rootsongjc commented on content/blog/kubernetes-ingress-controller-deployment-and-ha.md
> +- 在一些老版本的ingress nginx的log里会一直刷找不到ingress-nginx的svc不处理的话会狂刷log导致机器load过高,创建一个同名的svc即可解决,例如创建一个不带选择器clusterip为null的，新版本则不会
如果文中有参考的内容，可以在最后加个“参考”小结。

2019-04-15 13:10 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard
> +title: "k8s dashboard在ssl的各种场景下的手动部署"
建议标题使用 Kubernetes 全称，显得更正规些。

2019-04-15 13:12 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard
> +```
所有的代码片段都需要指明所用的语言，若无的话默认写`bash`

2019-04-15 13:12 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard
> +### 默认自带的https
不论几级标题下面都需要空一个空行。

2019-04-15 13:12 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard
> +![pic1](https://ws3.sinaimg.cn/large/005BYqpggy1g22j058fljj30l30grjsz.jpg)
图片的 alt 信息需要指明。

2019-04-15 13:13 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard
> +```
所有的代码片段前后都留一个空行。

2019-04-15 13:13 UTC, rootsongjc commented
文件名没加 `.md` 后缀。

2019-04-15 13:14 UTC, rootsongjc requested changes
需要修改文件名并修正文章格式。

2019-04-16 01:41 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
> +旨在面向新手讲解手动部署过程，本文dashboard的暴露不会用nodePort(不喜欢使用它)和apiserver的web proxy代理也就是`/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`这种
这后面是不是多了一个换行？

2019-04-16 01:42 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
> -![pic4](https://ws3.sinaimg.cn/large/005BYqpgly1g22j0598m4j31hc0n3wfi.jpg)
全文所有图片的上下都增加一个空行。

2019-04-16 01:42 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
>  上面直接dashboard使用域名证书会有单点故障，所以实际应用我们可以用高可用的ingress nginx(详见之前的文章)来代理集群内部的dashboard
全文中的括号需要换成中文样式。

2019-04-16 01:42 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
>  参考:
参考应该作为一个二级标题。

2019-04-16 01:43 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
> +![browser-cannot-continue](https://ws3.sinaimg.cn/large/005BYqpggy1g22j058fljj30l30grjsz.jpg)
图片的标题可以使用中文描述。

2019-04-16 01:44 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
>  这里我是使用的下面这种方式暴露出去，也就意味着我们不需要svc可以删掉官方yaml里最后那段`Dashboard Service`，访问的话用node的ip带上端口访问即可，改成大概下面这样
每句话最后都都需要增加标点，段落之间要换行。

2019-04-16 01:44 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
>  部署的yaml的话不推荐直接使用官方的yaml，我们需要看场景修改或者删减一些东西
不换行的段落请使用标点符号分隔或者使用列表。

2019-04-16 01:45 UTC, zhangguanzhang commented on content/blog/General-kubernetes-dashboard.md
> -![pic4](https://ws3.sinaimg.cn/large/005BYqpgly1g22j0598m4j31hc0n3wfi.jpg)
好的

2019-04-16 02:06 UTC, zhangguanzhang commented
这次应该改好了

2019-04-16 03:02 UTC, chlins commented on content/blog/kubernetes-ingress-controller-deployment-and-ha.md
> +- 在一些老版本的ingress nginx的log里会一直刷找不到ingress-nginx的svc不处理的话会狂刷log导致机器load过高,创建一个同名的svc即可解决,例如创建一个不带选择器clusterip为null的，新版本则不会
建议在"找不到ingress-nginx的svc"后面加个逗号。

2019-04-16 03:30 UTC, zhangguanzhang commented on content/blog/kubernetes-ingress-controller-deployment-and-ha.md
> +- 在一些老版本的ingress nginx的log里会一直刷找不到ingress-nginx的svc不处理的话会狂刷log导致机器load过高,创建一个同名的svc即可解决,例如创建一个不带选择器clusterip为null的，新版本则不会
修改好了

2019-04-16 06:18 UTC, rootsongjc commented on content/blog/General-kubernetes-dashboard.md
> +- https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/tls-termination
参考给出连接的标题和链接的域名，格式如下
- [TLS termination - github.com](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/tls-termination)

2019-04-16 07:01 UTC, rootsongjc commented
两篇文章最好分两个 PR 提交。

2019-04-16 07:10 UTC, chlins approved these changes

2019-04-16 07:27 UTC, rootsongjc commented
文中很多括号需要修改为中文格式。

2019-04-16 08:02 UTC, zhangguanzhang commented
我关闭掉这个，让后分两个提

2019-04-16 08:02 UTC, closed without merging