Translation: Three Technical Benefits of Service Meshes and their Operational Limitations, Part 2 #74
servicemesher/website pull request #89
Opened 2019-07-31 15:26 UTC by malphi

请审校者在合并该 PR 前需要检查以下内容：

- [ ] Header 设置正确，包括文章的类型、tag、分类、作者、译者、摘要、reviewer 发布时间等信息
- [ ] 关联 Issue 编号 [#${ISSUE_ID}](https://github.com/servicemesher/website/issues/${ISSUE_ID})
- [ ] 该 PR Assigned 给了提交者
- [ ] 指定了 Reviewer
- [ ] 为 PR 明确了 label 信息，如 categories、kind、size、tag、status
- [ ] 所有代码片段都指定了代码语言
- [ ] 翻译的文章添加了**编者按**
- [ ] 文章遵守了路径规范  `YEAR/MONTH/TITLE/index.md`，例如 `2019/04/new-blog/index.md`
- [ ] 图片保存了在 GitHub上，跟文章在同级目录
- [ ] 文章标题简短且语义明确
- [ ] 文章语句通顺，没有语病和格式问题
- [ ] 文中没有不可达的链接
- [ ] 提交者同意授权 ServiceMesher 公众号和 [http://www.servicemesher.com](http://www.servicemesher.com) 发布我原创或翻译的文章

当所有以上问题都确定之后，可以由管理者合并 PR 并关闭关联 issue。

2019-07-31 15:27 UTC, malphi commented
/assign @mesher-bot

2019-07-31 15:32 UTC, malphi commented
译者注：
1. ”federated, organically evolving service architectures “ 的翻译不太确定，暂时翻译成 关联、有机发展的，请reviewer确认。
2. 本文最后有一个iframe内嵌的video，请确认是否可以正常显示。
3. 使用了part1的编者按，请确认是否需要。

2019-08-01 01:52 UTC, rootsongjc commented
@malphi 视频嵌入的有问题，显示的位置错乱，请在这里预览：https://deploy-preview-89--servicemesher.netlify.com/blog/service-mesh-istio-limits-and-benefits-part-2/

2019-08-01 01:58 UTC, GuangmingLuo commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +<iframe src="https://player.vimeo.com/video/343154979?title=0&amp;profile=0&amp;byline=0&amp;dnt=1&amp;autoplay=1&amp;muted=1&amp;loop=1" allow="autoplay; fullscreen" allowfullscreen="" style="box-si
这个iframe的style设置的有些问题，显示的时候跳到了文章开头去了

2019-08-01 01:58 UTC, GuangmingLuo commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +这种将策略应用于任意服务交互集的能力的缺乏也使得策略的分层变得极其困难。例如，当一个[壁](https://glasnostic.com/blog/preventing-systemic-failure-bulkheads)在两个可用性区域之间，但一个关键服务需要能够在需要是故障转移，这几乎不可能找到正确的服务网格规则的阈值，特别是自动扩展的部署情况下。
壁->bulkhead或者舱壁， 建议全文的backpressure 和 bulkhead不译。

2019-08-01 01:58 UTC, GuangmingLuo commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +banner: "/img/blog/banners/Rundale-Palace-service-mesh.png"
建议采用不同的banner吧，避免读者误解发了两篇相同的文章

2019-08-01 02:01 UTC, rootsongjc commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +<iframe src="https://player.vimeo.com/video/343154979?title=0&amp;profile=0&amp;byline=0&amp;dnt=1&amp;autoplay=1&amp;muted=1&amp;loop=1" allow="autoplay; fullscreen" allowfullscreen="" style="box-si
style 写的不对吧

2019-08-01 02:26 UTC, malphi commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +banner: "/img/blog/banners/Rundale-Palace-service-mesh.png"
DONE

2019-08-01 02:26 UTC, malphi commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +这种将策略应用于任意服务交互集的能力的缺乏也使得策略的分层变得极其困难。例如，当一个[壁](https://glasnostic.com/blog/preventing-systemic-failure-bulkheads)在两个可用性区域之间，但一个关键服务需要能够在需要是故障转移，这几乎不可能找到正确的服务网格规则的阈值，特别是自动扩展的部署情况下。
DONE

2019-08-01 02:27 UTC, malphi commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +<iframe src="https://player.vimeo.com/video/343154979?title=0&amp;profile=0&amp;byline=0&amp;dnt=1&amp;autoplay=1&amp;muted=1&amp;loop=1" allow="autoplay; fullscreen" allowfullscreen="" style="box-si
DONE

2019-08-01 02:40 UTC, GuangmingLuo commented
建议更新一下Header里面的时间、摘要、reviewer等信息、关联issue编号，提交者同意授权。

2019-08-01 02:44 UTC, malphi commented
> 建议更新一下Header里面的时间、摘要、reviewer等信息、关联issue编号，提交者同意授权。

DONE

2019-08-01 03:48 UTC, rootsongjc commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +<figure id="figure-1">
iframe 这样写我检测过没有问题：
```html
<div class="video-wrapper" style="position: relative;padding-bottom: 56.25%;padding-top: 25px;height: 0;">
<iframe src="https://player.vimeo.com/video/343154979?title=0&amp;profile=0&amp;byline=0&amp;dnt=1&amp;autoplay=1&amp;muted=1&amp;loop=1" allow="autoplay; fullscreen" allowfullscreen="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;"></iframe>
</div>
```

2019-08-01 03:49 UTC, malphi commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +<figure id="figure-1">
我试试

2019-08-01 03:49 UTC, rootsongjc commented on content/blog/service-mesh-istio-limits-and-benefits-part-2/index.md
> +---
front matters 配置有问题，所有指需要用引号括起来，categories 是数组形式。下面的是正确的配置：
```yaml
---
originallink: "https://glasnostic.com/blog/service-mesh-istio-limits-and-benefits-part-2"
author: "Tobias Kunze"
date: 2019-08-01T10:42:00+08:00
draft: false
banner: "/img/blog/banners/limitandbenefit.jpg"
translator: "马若飞"
translatorlink: https://github.com/malphi
reviewer:  ["罗广明"]
reviewerlink:  ["https://github.com/GuangmingLuo"]
title: "服务网格的三个技术优势及其运维局限-第2部分"
description: "本文结合当前服务网格的形势，分析了服务网格的局限性，以及其带来的三个有价值的好处：可观测性、流量控制和安全。"
categories: ["Service Mesh"]
tags: ["Service Mesh"]
---
```

2019-08-01 03:49 UTC, rootsongjc requested changes
需要修front matter配置及 iframe 样式。

2019-08-01 03:59 UTC, rootsongjc approved these changes
/LGTM

2019-08-01 04:01 UTC, rootsongjc commented
/LGTM

2019-08-01 04:01 UTC, merged